name: CI/CD
on:
  push:
    branches:
      - master
jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: check files
        run: npm run eslint
      - name: build project
        run: npm run build
        env: 
          START_URL: ${{ secrets.START_URL }}
      - name: Deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./dist/*
          remote_path: /var/www/html/todo-frontend/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
