name: CI/CD
on: [workflow_dispatch]
jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr
          path: ./
          remote_path: /var/www/html/todo-frontend/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}